name: Pokedex CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
name: Github checkout
    uses: actions/checkout@v4

    
name: Setup Node.js
    uses: actions/setup-node@v4

    
name: Install dependencies
    run: npm ci

    
name: Build project
    run: npm run build

    
name: Message de fin
    run : echo "ğŸ‰ Tout est Ok !"